version: '3.8'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:10.0.1
    restart: always
    secrets:
      - keycloak-password
      - postgres-password
    depends_on:
      - db
    ports:
      - "8081:8080"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD_FILE: /run/secrets/keycloak-password
      DB_VENDOR: POSTGRES
      DB_ADDR: db
      DB_DATABASE: keycloak
      DB_SCHEMA: public
      DB_USER: postgres
      DB_PASSWORD_FILE: /run/secrets/postgres-password

  db:
    image: postgres
    restart: always
    secrets:
      - postgres-password
    ports:
      - "5433:5432"
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-password
      POSTGRES_MULTIPLE_DATABASES: vanilla,keycloak

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 5434:8080

secrets:
  postgres-password:
    file: ./secrets/postgres-password
  keycloak-password:
    file: ./secrets/keycloak-password
